// Code generated by protoc-gen-go.
// source: user_extra.proto
// DO NOT EDIT!

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type GetUserExtraRequest struct {
	Uid int32 `protobuf:"varint,1,opt,name=uid" json:"uid,omitempty"`
}

func (m *GetUserExtraRequest) Reset()                    { *m = GetUserExtraRequest{} }
func (m *GetUserExtraRequest) String() string            { return proto.CompactTextString(m) }
func (*GetUserExtraRequest) ProtoMessage()               {}
func (*GetUserExtraRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

type UserExtraObject struct {
	Key2     int32  `protobuf:"varint,1,opt,name=key2" json:"key2,omitempty"`
	Key1     int32  `protobuf:"varint,2,opt,name=key1" json:"key1,omitempty"`
	UpdateAt string `protobuf:"bytes,3,opt,name=update_at,json=updateAt" json:"update_at,omitempty"`
	Uid      int32  `protobuf:"varint,4,opt,name=uid" json:"uid,omitempty"`
	CreateAt string `protobuf:"bytes,5,opt,name=create_at,json=createAt" json:"create_at,omitempty"`
}

func (m *UserExtraObject) Reset()                    { *m = UserExtraObject{} }
func (m *UserExtraObject) String() string            { return proto.CompactTextString(m) }
func (*UserExtraObject) ProtoMessage()               {}
func (*UserExtraObject) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

type CreateUserExtraResponse struct {
	AffectNum int64            `protobuf:"varint,1,opt,name=affect_num,json=affectNum" json:"affect_num,omitempty"`
	UserExtra *UserExtraObject `protobuf:"bytes,2,opt,name=user_extra,json=userExtra" json:"user_extra,omitempty"`
}

func (m *CreateUserExtraResponse) Reset()                    { *m = CreateUserExtraResponse{} }
func (m *CreateUserExtraResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateUserExtraResponse) ProtoMessage()               {}
func (*CreateUserExtraResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

func (m *CreateUserExtraResponse) GetUserExtra() *UserExtraObject {
	if m != nil {
		return m.UserExtra
	}
	return nil
}

type UpdateUserExtraRequest struct {
	Uid       int32            `protobuf:"varint,1,opt,name=uid" json:"uid,omitempty"`
	UserExtra *UserExtraObject `protobuf:"bytes,2,opt,name=user_extra,json=userExtra" json:"user_extra,omitempty"`
}

func (m *UpdateUserExtraRequest) Reset()                    { *m = UpdateUserExtraRequest{} }
func (m *UpdateUserExtraRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateUserExtraRequest) ProtoMessage()               {}
func (*UpdateUserExtraRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

func (m *UpdateUserExtraRequest) GetUserExtra() *UserExtraObject {
	if m != nil {
		return m.UserExtra
	}
	return nil
}

type UpdateUserExtraResponse struct {
	AffectNum int64            `protobuf:"varint,1,opt,name=affect_num,json=affectNum" json:"affect_num,omitempty"`
	UserExtra *UserExtraObject `protobuf:"bytes,2,opt,name=user_extra,json=userExtra" json:"user_extra,omitempty"`
}

func (m *UpdateUserExtraResponse) Reset()                    { *m = UpdateUserExtraResponse{} }
func (m *UpdateUserExtraResponse) String() string            { return proto.CompactTextString(m) }
func (*UpdateUserExtraResponse) ProtoMessage()               {}
func (*UpdateUserExtraResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{4} }

func (m *UpdateUserExtraResponse) GetUserExtra() *UserExtraObject {
	if m != nil {
		return m.UserExtra
	}
	return nil
}

type QueryUserExtraResponse struct {
	UserExtras []*UserExtraObject `protobuf:"bytes,1,rep,name=user_extras,json=userExtras" json:"user_extras,omitempty"`
}

func (m *QueryUserExtraResponse) Reset()                    { *m = QueryUserExtraResponse{} }
func (m *QueryUserExtraResponse) String() string            { return proto.CompactTextString(m) }
func (*QueryUserExtraResponse) ProtoMessage()               {}
func (*QueryUserExtraResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{5} }

func (m *QueryUserExtraResponse) GetUserExtras() []*UserExtraObject {
	if m != nil {
		return m.UserExtras
	}
	return nil
}

func init() {
	proto.RegisterType((*GetUserExtraRequest)(nil), "pb.GetUserExtraRequest")
	proto.RegisterType((*UserExtraObject)(nil), "pb.UserExtraObject")
	proto.RegisterType((*CreateUserExtraResponse)(nil), "pb.CreateUserExtraResponse")
	proto.RegisterType((*UpdateUserExtraRequest)(nil), "pb.UpdateUserExtraRequest")
	proto.RegisterType((*UpdateUserExtraResponse)(nil), "pb.UpdateUserExtraResponse")
	proto.RegisterType((*QueryUserExtraResponse)(nil), "pb.QueryUserExtraResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion1

// Client API for UserExtra service

type UserExtraClient interface {
	GetUserExtra(ctx context.Context, in *GetUserExtraRequest, opts ...grpc.CallOption) (*UserExtraObject, error)
	UpdateUserExtra(ctx context.Context, in *UpdateUserExtraRequest, opts ...grpc.CallOption) (*UpdateUserExtraResponse, error)
	CreateUserExtra(ctx context.Context, in *UserExtraObject, opts ...grpc.CallOption) (*CreateUserExtraResponse, error)
	QueryUserExtra(ctx context.Context, in *UserExtraObject, opts ...grpc.CallOption) (*QueryUserExtraResponse, error)
	QueryOneUserExtra(ctx context.Context, in *UserExtraObject, opts ...grpc.CallOption) (*UserExtraObject, error)
}

type userExtraClient struct {
	cc *grpc.ClientConn
}

func NewUserExtraClient(cc *grpc.ClientConn) UserExtraClient {
	return &userExtraClient{cc}
}

func (c *userExtraClient) GetUserExtra(ctx context.Context, in *GetUserExtraRequest, opts ...grpc.CallOption) (*UserExtraObject, error) {
	out := new(UserExtraObject)
	err := grpc.Invoke(ctx, "/pb.UserExtra/GetUserExtra", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userExtraClient) UpdateUserExtra(ctx context.Context, in *UpdateUserExtraRequest, opts ...grpc.CallOption) (*UpdateUserExtraResponse, error) {
	out := new(UpdateUserExtraResponse)
	err := grpc.Invoke(ctx, "/pb.UserExtra/UpdateUserExtra", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userExtraClient) CreateUserExtra(ctx context.Context, in *UserExtraObject, opts ...grpc.CallOption) (*CreateUserExtraResponse, error) {
	out := new(CreateUserExtraResponse)
	err := grpc.Invoke(ctx, "/pb.UserExtra/CreateUserExtra", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userExtraClient) QueryUserExtra(ctx context.Context, in *UserExtraObject, opts ...grpc.CallOption) (*QueryUserExtraResponse, error) {
	out := new(QueryUserExtraResponse)
	err := grpc.Invoke(ctx, "/pb.UserExtra/QueryUserExtra", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userExtraClient) QueryOneUserExtra(ctx context.Context, in *UserExtraObject, opts ...grpc.CallOption) (*UserExtraObject, error) {
	out := new(UserExtraObject)
	err := grpc.Invoke(ctx, "/pb.UserExtra/QueryOneUserExtra", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for UserExtra service

type UserExtraServer interface {
	GetUserExtra(context.Context, *GetUserExtraRequest) (*UserExtraObject, error)
	UpdateUserExtra(context.Context, *UpdateUserExtraRequest) (*UpdateUserExtraResponse, error)
	CreateUserExtra(context.Context, *UserExtraObject) (*CreateUserExtraResponse, error)
	QueryUserExtra(context.Context, *UserExtraObject) (*QueryUserExtraResponse, error)
	QueryOneUserExtra(context.Context, *UserExtraObject) (*UserExtraObject, error)
}

func RegisterUserExtraServer(s *grpc.Server, srv UserExtraServer) {
	s.RegisterService(&_UserExtra_serviceDesc, srv)
}

func _UserExtra_GetUserExtra_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(GetUserExtraRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(UserExtraServer).GetUserExtra(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _UserExtra_UpdateUserExtra_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(UpdateUserExtraRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(UserExtraServer).UpdateUserExtra(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _UserExtra_CreateUserExtra_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(UserExtraObject)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(UserExtraServer).CreateUserExtra(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _UserExtra_QueryUserExtra_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(UserExtraObject)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(UserExtraServer).QueryUserExtra(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _UserExtra_QueryOneUserExtra_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(UserExtraObject)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(UserExtraServer).QueryOneUserExtra(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

var _UserExtra_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.UserExtra",
	HandlerType: (*UserExtraServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUserExtra",
			Handler:    _UserExtra_GetUserExtra_Handler,
		},
		{
			MethodName: "UpdateUserExtra",
			Handler:    _UserExtra_UpdateUserExtra_Handler,
		},
		{
			MethodName: "CreateUserExtra",
			Handler:    _UserExtra_CreateUserExtra_Handler,
		},
		{
			MethodName: "QueryUserExtra",
			Handler:    _UserExtra_QueryUserExtra_Handler,
		},
		{
			MethodName: "QueryOneUserExtra",
			Handler:    _UserExtra_QueryOneUserExtra_Handler,
		},
	},
	Streams: []grpc.StreamDesc{},
}

var fileDescriptor1 = []byte{
	// 351 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xb4, 0x53, 0x5d, 0x4b, 0x02, 0x41,
	0x14, 0x4d, 0x57, 0xa3, 0xbd, 0x46, 0xda, 0x15, 0x54, 0x94, 0x20, 0xf6, 0xa5, 0x9e, 0x04, 0xb7,
	0x9e, 0x0b, 0x11, 0xe9, 0x25, 0x94, 0x16, 0x7c, 0x6d, 0xd9, 0xd5, 0x11, 0xfa, 0x70, 0x77, 0xdb,
	0x99, 0x81, 0xfc, 0x01, 0xfd, 0xd5, 0x7e, 0x47, 0xb3, 0x33, 0xdb, 0xf8, 0x35, 0x22, 0x04, 0xbd,
	0x0d, 0xe7, 0x1c, 0xcf, 0x3d, 0xf7, 0x78, 0x17, 0x6a, 0x9c, 0x92, 0xd4, 0x27, 0x9f, 0x2c, 0x0d,
	0xba, 0x49, 0x1a, 0xb3, 0x18, 0x8b, 0x49, 0xe8, 0x5c, 0x41, 0xfd, 0x81, 0xb0, 0x89, 0xa0, 0x86,
	0x19, 0xe3, 0x91, 0x0f, 0x4e, 0x28, 0xc3, 0x1a, 0x58, 0xfc, 0x65, 0xd6, 0x2a, 0x5c, 0x16, 0xae,
	0xcb, 0x5e, 0xf6, 0x74, 0xbe, 0x0a, 0x50, 0xd5, 0xb2, 0x71, 0xf8, 0x4a, 0xa6, 0x0c, 0x11, 0x4a,
	0x6f, 0x64, 0xe9, 0xe6, 0x32, 0xf9, 0xce, 0xb1, 0x5e, 0xab, 0xa8, 0xb1, 0x1e, 0x76, 0xc0, 0xe6,
	0xc9, 0x2c, 0x60, 0xc4, 0x0f, 0x58, 0xcb, 0x12, 0x84, 0xed, 0x9d, 0x28, 0xa0, 0xaf, 0x47, 0x95,
	0xf4, 0xa8, 0x4c, 0x3e, 0x4d, 0x49, 0x2e, 0x2f, 0x2b, 0xb9, 0x02, 0xfa, 0xcc, 0x79, 0x87, 0xe6,
	0x40, 0xbe, 0xd7, 0x32, 0xd3, 0x24, 0x8e, 0x28, 0xc1, 0x0b, 0x80, 0x60, 0x3e, 0x17, 0xc1, 0xfc,
	0x88, 0x2f, 0x64, 0x28, 0xcb, 0xb3, 0x15, 0x32, 0xe2, 0x0b, 0x74, 0x01, 0x56, 0x15, 0xc8, 0x7c,
	0x15, 0xb7, 0xde, 0x4d, 0xc2, 0xee, 0xd6, 0x5a, 0x9e, 0xcd, 0x7f, 0x01, 0xe7, 0x19, 0x1a, 0x13,
	0x19, 0xf4, 0x70, 0x43, 0x7f, 0xf2, 0x17, 0xdb, 0xec, 0xf8, 0xff, 0xdf, 0x36, 0x23, 0x68, 0x3c,
	0x71, 0x92, 0x2e, 0x77, 0x87, 0xdd, 0x42, 0x65, 0xe5, 0x46, 0xc5, 0x34, 0x6b, 0x9f, 0x1d, 0x68,
	0x3b, 0xea, 0x7e, 0x17, 0xc1, 0xd6, 0x3c, 0xde, 0xc1, 0xe9, 0xfa, 0x29, 0x61, 0x33, 0xfb, 0xb9,
	0xe1, 0xb8, 0xda, 0x26, 0x5f, 0xe7, 0x08, 0x1f, 0xc5, 0x81, 0x6d, 0x76, 0x81, 0x6d, 0xa9, 0x34,
	0xfe, 0x01, 0xed, 0x8e, 0x91, 0x53, 0xfb, 0x08, 0xb7, 0x21, 0x54, 0xb7, 0xee, 0x04, 0x4d, 0x73,
	0x95, 0xcd, 0x9e, 0x8b, 0x12, 0x36, 0x03, 0x38, 0xdb, 0xac, 0xcc, 0xec, 0x22, 0x83, 0x9a, 0xbb,
	0x15, 0x26, 0xf7, 0x70, 0x2e, 0xb9, 0x71, 0x74, 0x28, 0x8d, 0xb9, 0x9a, 0xf0, 0x58, 0x7e, 0xb0,
	0x37, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x53, 0xfa, 0x54, 0x32, 0xc4, 0x03, 0x00, 0x00,
}
